version: 2

jobs:
  test-node10:
    docker:
      - image: circleci/node:10.19
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-node10-{{ arch }}-{{ checksum "yarn.lock" }}
            - dependencies-node10-{{ arch }}
      - run:
          name: Install dependencies
          command: yarn --prefer-offline --pure-lockfile
      - save_cache:
          key: dependencies-node10-{{ arch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run:
          name: lint code
          command: yarn run lint
      - run:
          name: tests
          command: yarn run test
      - run:
          name: Check nothing was forget before commit
          command: yarn run repository-check-dirty

  test-node12:
    docker:
      - image: circleci/node:12.16
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-node12-{{ arch }}-{{ checksum "yarn.lock" }}
            - dependencies-node12-{{ arch }}
      - run:
          name: Install dependencies
          command: yarn --prefer-offline --pure-lockfile
      - save_cache:
          key: dependencies-node12-{{ arch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run:
          name: tests
          command: yarn run test

workflows:
  version: 2

  tests:
    jobs:
      - test-node10
      - test-node12
